package com.example.posapp.models

data class Product(
    val image: String, // URL or resource ID
    val color: String,
    val id: Int,
    val type: String,
    val group_id: Int,
    val unit_id: Int,
    val name: Name,
    val description: Description,
    val code: String,
    val code2: String,
    val code3: String,
    val code5: String,
    val code6: String,
    val code7: String,
    val code8: String,
    val extra_field1_id: Int,
    val extra_field2_id: Int,
    val extra_field3_id: Int,
    val extra_field4_id: Int,
    val supplier_code: String,
    val tax_rate_id: Int,
    val price: Double,
    val suggested_retail_price: Int,
    val price_with_tax: Int,
    val net_weight: Int,
    val gross_weight: Int,
    val length: Int,
    val width: Int,
    val height: Int,
    val is_gift_card: Int,
    val non_discountable: Int,
    val non_refundable: Int,
    val volume: Int,
    val category_id: Int,
    val brand_id: Int,
    val supplier_id: Int,
    val priority_group_id: Int,
    val country_of_origin_id: Int,
    val manufacturer_name: String,
    val cost: Int,
    val status: String,
    val displayed_in_webshop: Int,
    val sold_in_packages: Int,
    val location_in_warehouse_id: Int,
    val location_in_warehouse_text: String,
    val parent_product_id: Int,
    val deposit_fee_id: Int,
    val family_id: Int,
    val age_restriction: Int,
    val packing_not_required: Int,
    val has_serial_numbers: Int,
    val delivery_time: String,
    val packaging_type: String,
    val alcohol_registry_number: String,
    val alcohol_percentage: String,
    val batches: String,
    val excise_declaration_number: String,
    val tax_free: Int,
    val is_regular_gift_card: Int,
    val reward_points_not_allowed: Int,
    val non_stock_product: Int,
    val cashier_must_enter_price: Int,
    val labels_not_needed: Int,
    val deposit_fee_amount: Int,
    val product_reorder_multiples: Int,
    val sales_package_clear_brown_glass: Int,
    val sales_package_green_other_glass: Int,
    val sales_package_plastic_pp_pe: Int,
    val sales_package_plastic_pet: Int,
    val sales_package_metal_fe: Int,
    val sales_package_metal_al: Int,
    val sales_package_other_metal: Int,
    val sales_package_cardboard: Int,
    val sales_package_wood: Int,
    val group_package_paper: Int,
    val group_package_plastic: Int,
    val group_package_metal: Int,
    val group_package_wood: Int,
    val transport_package_wood: Int,
    val transport_package_plastic: Int,
    val transport_package_cardboard: Int,
    val added: Int,
    val addedby: String,
    val changed: Int,
    val changedby: String,
    val supplier_name: String
)

data class Name(
    val en: String
)

data class Description(
    val en: LanguageDescription,
    val ru: LanguageDescription,
    val fi: LanguageDescription
)

data class LanguageDescription(
    val plain_text: String,
    val html: String
)